### ISSUE TITLE
missing cloneElement and toChildArray

### ISSUE THREAD

**Issue by badpenguin** [mujahidfa/preact-htm-signals-standalone#1]
Hi, I had to patch to add cloneElement and toChildarray to the exports to make it work.

Also those steps where required to migrate it:
```
//import htm from 'htm';
//const html = htm.bind(h);
import {html} from 'htm';
```
because htm is not exported.

**Comment by mujahidfa** [comment]
`cloneElement`, `toChildarray` and `htm` are exposed in the latest release `v0.0.16`.
